In [24]:
%display latex

In [ ]:
var('x,t')
implicit_multiplication(10)

In [ ]:
R.<x, t> = PolynomialRing(QQ)
f = (x^6 - 5*x^4 + 6*x^2 - 1)*t^5 + (x^5 - 4*x^3 + 3*x^2)*t^6
g = x*t^2-x^2*t+x

h = f.quo_rem(g)
show(h[0])
show('\n')
show(h[1])

In [ ]:
p = f // g
p.

In [ ]:
p.reduced_form()

In [ ]:
p.simplify()

In [68]:
A = Matrix([[1,2],[7,4],[-1,2]])
b = vector([3,2,1])
show(A)
show(b)

[ 1  2]
[ 7  4]
[-1  2]

(3, 2, 1)

In [69]:
(A.T*A).rref()

[1 0]
[0 1]

In [70]:
(A.T * A)^(-1) * A.T * b

(-8/55, 46/55)

In [ ]:
A = Matrix([[1,2,3],[3,2,1],[1,1,1]])
w = vector([1,1,-4])

In [48]:
A = Matrix([[2/3, 2/3, 1/3], [1/sqrt(2), -1/sqrt(2), 0]])

In [56]:
x = vector([1,2,2])
p = (A.T*A) *x
show(p-x)
(p-x) * (1/3)*vector([2,2,1])

(5/18, 5/18, -10/9)

0

In [111]:
A = Matrix(SR, [[-1,3], [1,5]])
show(A)

[-1  3]
[ 1  5]

In [116]:
a = A.columns()
abar = [v.normalized() for v in a]

In [117]:
show(a)
show(abar)

[(-1, 1), (3, 5)]

[(-1/2*sqrt(2), 1/2*sqrt(2)), (3/34*sqrt(34), 5/34*sqrt(34))]

In [194]:
def P(e,a):
    return (e*a)*(e.normalized())

In [120]:
u1 = (a[1] - P(u0, a[1])).normalized()
show(u1)

(1/2*sqrt(2), 1/2*sqrt(2))

In [107]:
vector([1,1])*vector([1,2])*vector([3,2])

(9, 6)

In [195]:
def GS(a):
    u = [None] * len(a)
    e = [None] * len(a)
    for k in range(len(a)):
        projs = [P(u[j], a[k]) for j in range(k)]
        show(k, projs)
        u[k] = (a[k] - sum(projs))
        e[k] = (u[k]).normalized()
    return (u, e)

In [197]:
A = Matrix(SR, [[12,-51,4], [6,167,-68],[-4,24,-41]])
show(A)
GS(A.columns())
print "done"

[ 12 -51   4]
[  6 167 -68]
[ -4  24 -41]

0 []

1 [(252, 126, -84)]

2 [(-168, -84, 56),
 (182406/1073*sqrt(2146), -24682/1073*sqrt(2146), -65016/1073*sqrt(2146))]

done


In [142]:
sum([3*vector([1,1]), -1*vector([1,2]), 2*vector([3,2])])

(8, 5)

In [136]:
range(1)

[0]

In [201]:
u1bar = vector([12,6,-4]).normalized()

In [202]:
u1 = vector([12,6,-4])
a2 = vector([-51,167,24])
u1*a2

294

In [204]:
a2-(u1*a2)*u1bar

(-303, 41, 108)

101/23

In [212]:
A = Matrix([[-1,1],[1,1]])
A.T

[-1  1]
[ 1  1]

In [213]:
A * Matrix([[-1,3], [1,5]])

[2 2]
[0 8]

In [220]:
A = Matrix(SR, [[2,-2], [1,2]])
X = A.T * A
show(X)

[ 5 -2]
[-2  8]

In [221]:
import numpy as np

In [223]:
X.SVD()

AttributeError: 'sage.matrix.matrix_symbolic_dense.Matrix_symbolic_dense' object has no attribute 'SVD'